"""empty message

Revision ID: a572294361c5
Revises: 2b9e51df1cdd
Create Date: 2021-11-13 14:53:30.697761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a572294361c5'
down_revision = '2b9e51df1cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('userName', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'userName')
    # ### end Alembic commands ###
