"""empty message

Revision ID: 439628456eb7
Revises: 
Create Date: 2021-11-14 18:22:12.695600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439628456eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_messages', sa.Column('username', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('messages', sa.Column('userName', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'userName')
    op.drop_column('messages', 'createdAt')
    op.drop_column('dm_messages', 'username')
    # ### end Alembic commands ###
