"""empty message

Revision ID: 0a185f7d97ae
Revises: d18a51b4ed80
Create Date: 2021-11-10 15:24:52.468705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a185f7d97ae'
down_revision = 'd18a51b4ed80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dm_messages_receiverId_fkey', 'dm_messages', type_='foreignkey')
    op.drop_column('dm_messages', 'receiverId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_messages', sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('dm_messages_receiverId_fkey', 'dm_messages', 'users', ['receiverId'], ['id'])
    # ### end Alembic commands ###
