"""empty message

Revision ID: 1103dcc996ec
Revises: 
Create Date: 2021-11-10 12:33:21.288353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1103dcc996ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('banner', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dm_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('dm_server_Id', sa.Integer(), nullable=True),
    sa.Column('imageUrl', sa.String(length=200), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dm_server_Id'], ['dm_servers.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dm_messages')
    op.drop_table('dm_servers')
    # ### end Alembic commands ###
