"""empty message

Revision ID: d18a51b4ed80
Revises: 
Create Date: 2021-11-10 13:46:20.195409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18a51b4ed80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_servers', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dm_servers', 'name')
    # ### end Alembic commands ###
